# Site settings
title: Kode Kitab
description: > # this means to ignore newlines until "baseurl:"
  
  Kode kitab is a code book, literally. Other than an alliteration in 
  somewhat English and the Hindi language this is a place for me to pen 
  down my thoughts and lessons learnt while creating software so that 
  I do not forget.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hemantkumar.net" # the base hostname & protocol for your site
twitter_username: _hemantksingh
github_username:  hemantksingh
linkedin_username: hemantkrsingh

# Build settings
markdown: kramdown