# Site settings
title: Hemant Kumar
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hemantkumar.net" # the base hostname & protocol for your site
twitter_username: _hemantksingh
github_username:  hemantksingh
linkedin_username: hemantkrsingh
footer: © Hemant Kumar | Hosted by GitHub and powered by Jekyll
markdown: kramdown
permalink: /:title.html
gems:
  - jekyll-redirect-from
