# Site settings
title: Hemant Kumar
description: > # this means to ignore newlines until "baseurl:"
  Political animal, Software Engineer, Thoughtworker and a recalcitrant par excellence
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hemantkumar.net" # the base hostname & protocol for your site
twitter_username: _hemantksingh
github_username:  hemantksingh
linkedin_username: hemantkrsingh

# Build settings
markdown: kramdown